# Generated by Django 4.2 on 2024-05-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_cmc', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
