# Generated by Django 4.2 on 2024-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecoin',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
