# Generated by Django 4.2 on 2024-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_alter_activecoin_id_in_cmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecoin',
            name='id_in_cmc',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='activecoin',
            name='rank',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
